In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
property_2016 = pd.read_csv('../data/properties_2016.csv')
property_2016.head()

/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (22,32,34,49,55) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,parcelid,airconditioningtypeid,architecturalstyletypeid,basementsqft,bathroomcnt,bedroomcnt,buildingclasstypeid,buildingqualitytypeid,calculatedbathnbr,decktypeid,...,numberofstories,fireplaceflag,structuretaxvaluedollarcnt,taxvaluedollarcnt,assessmentyear,landtaxvaluedollarcnt,taxamount,taxdelinquencyflag,taxdelinquencyyear,censustractandblock
0,10754147,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,9.0,2015.0,9.0,NaN,NaN,NaN,NaN
1,10759547,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,27516.0,2015.0,27516.0,NaN,NaN,NaN,NaN
2,10843547,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,650756.0,1413387.0,2015.0,762631.0,20800.37,NaN,NaN,NaN
3,10859147,NaN,NaN,NaN,0.0,0.0,3.0,7.0,NaN,NaN,...,1.0,NaN,571346.0,1156834.0,2015.0,585488.0,14557.57,NaN,NaN,NaN
4,10879947,NaN,NaN,NaN,0.0,0.0,4.0,NaN,NaN,NaN,...,NaN,NaN,193796.0,433491.0,2015.0,239695.0,5725.17,NaN,NaN,NaN

In [4]:
property_2017 = pd.read_csv('../data/properties_2017.csv')
property_2017.head()

/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (49) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,parcelid,airconditioningtypeid,architecturalstyletypeid,basementsqft,bathroomcnt,bedroomcnt,buildingclasstypeid,buildingqualitytypeid,calculatedbathnbr,decktypeid,...,numberofstories,fireplaceflag,structuretaxvaluedollarcnt,taxvaluedollarcnt,assessmentyear,landtaxvaluedollarcnt,taxamount,taxdelinquencyflag,taxdelinquencyyear,censustractandblock
0,10754147,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,9.0,2016.0,9.0,NaN,NaN,NaN,NaN
1,10759547,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,27516.0,2015.0,27516.0,NaN,NaN,NaN,NaN
2,10843547,NaN,NaN,NaN,0.0,0.0,5.0,NaN,NaN,NaN,...,1.0,NaN,660680.0,1434941.0,2016.0,774261.0,20800.37,NaN,NaN,NaN
3,10859147,NaN,NaN,NaN,0.0,0.0,3.0,6.0,NaN,NaN,...,1.0,NaN,580059.0,1174475.0,2016.0,594416.0,14557.57,NaN,NaN,NaN
4,10879947,NaN,NaN,NaN,0.0,0.0,4.0,NaN,NaN,NaN,...,1.0,NaN,196751.0,440101.0,2016.0,243350.0,5725.17,NaN,NaN,NaN

In [5]:
property_2016.shape

(2985217, 58)

In [6]:
property_2017.shape

(2985217, 58)

In [7]:
property_2016.columns

Index(['parcelid', 'airconditioningtypeid', 'architecturalstyletypeid',
       'basementsqft', 'bathroomcnt', 'bedroomcnt', 'buildingclasstypeid',
       'buildingqualitytypeid', 'calculatedbathnbr', 'decktypeid',
       'finishedfloor1squarefeet', 'calculatedfinishedsquarefeet',
       'finishedsquarefeet12', 'finishedsquarefeet13', 'finishedsquarefeet15',
       'finishedsquarefeet50', 'finishedsquarefeet6', 'fips', 'fireplacecnt',
       'fullbathcnt', 'garagecarcnt', 'garagetotalsqft', 'hashottuborspa',
       'heatingorsystemtypeid', 'latitude', 'longitude', 'lotsizesquarefeet',
       'poolcnt', 'poolsizesum', 'pooltypeid10', 'pooltypeid2', 'pooltypeid7',
       'propertycountylandusecode', 'propertylandusetypeid',
       'propertyzoningdesc', 'rawcensustractandblock', 'regionidcity',
       'regionidcounty', 'regionidneighborhood', 'regionidzip', 'roomcnt',
       'storytypeid', 'threequarterbathnbr', 'typeconstructiontypeid',
       'unitcnt', 'yardbuildingsqft17', 'yardbuildingsqft26', 'yearbuilt',
       'numberofstories', 'fireplaceflag', 'structuretaxvaluedollarcnt',
       'taxvaluedollarcnt', 'assessmentyear', 'landtaxvaluedollarcnt',
       'taxamount', 'taxdelinquencyflag', 'taxdelinquencyyear',
       'censustractandblock'],
      dtype='object')

In [9]:
property_2016.iloc[5,:]

parcelid                            10898347
airconditioningtypeid                    NaN
architecturalstyletypeid                 NaN
basementsqft                             NaN
bathroomcnt                              0.0
bedroomcnt                               0.0
buildingclasstypeid                      4.0
buildingqualitytypeid                    7.0
calculatedbathnbr                        NaN
decktypeid                               NaN
finishedfloor1squarefeet                 NaN
calculatedfinishedsquarefeet          2400.0
finishedsquarefeet12                     NaN
finishedsquarefeet13                     NaN
finishedsquarefeet15                  2400.0
finishedsquarefeet50                     NaN
finishedsquarefeet6                      NaN
fips                                  6037.0
fireplacecnt                             NaN
fullbathcnt                              NaN
garagecarcnt                             NaN
garagetotalsqft                          NaN
hashottuborspa                           NaN
heatingorsystemtypeid                    NaN
latitude                          34171873.0
longitude                       -118380906.0
lotsizesquarefeet                     2500.0
poolcnt                                  NaN
poolsizesum                              NaN
pooltypeid10                             NaN
pooltypeid2                              NaN
pooltypeid7                              NaN
propertycountylandusecode               1210
propertylandusetypeid                   31.0
propertyzoningdesc                      LAC4
rawcensustractandblock          60371252.001
regionidcity                         12447.0
regionidcounty                        3101.0
regionidneighborhood                 46795.0
regionidzip                          96446.0
roomcnt                                  0.0
storytypeid                              NaN
threequarterbathnbr                      NaN
typeconstructiontypeid                   NaN
unitcnt                                  NaN
yardbuildingsqft17                       NaN
yardbuildingsqft26                       NaN
yearbuilt                             1943.0
numberofstories                          1.0
fireplaceflag                            NaN
structuretaxvaluedollarcnt          176383.0
taxvaluedollarcnt                   283315.0
assessmentyear                        2015.0
landtaxvaluedollarcnt               106932.0
taxamount                            3661.28
taxdelinquencyflag                       NaN
taxdelinquencyyear                       NaN
censustractandblock                      NaN
Name: 5, dtype: object

In [11]:
property_2016['fips'].value_counts()

6037.0    2009362
6059.0     741565
6111.0     222853
Name: fips, dtype: int64

In [12]:
property_2016['pooltypeid10'].value_counts()

1.0    36939
Name: pooltypeid10, dtype: int64

In [13]:
property_2016['pooltypeid7'].value_counts()

1.0    485459
Name: pooltypeid7, dtype: int64

In [16]:
# remove
property_2016['propertyzoningdesc'].value_counts()

LAR1         275029
LAR3          67105
LARS          54859
LBR1N         52750
LAR2          48808
              ...
COCL-PRL*         1
SMM1-R3A*         1
RMR244*           1
GL-R-4*           1
MOR3P*            1
Name: propertyzoningdesc, Length: 5638, dtype: int64

In [17]:
# remove
property_2016['rawcensustractandblock'].value_counts()

6.059052e+07    1518
6.037920e+07    1455
6.059063e+07     895
6.037137e+07     886
6.037577e+07     825
                ...
6.037651e+07       1
6.037464e+07       1
6.037404e+07       1
6.037911e+07       1
6.037800e+07       1
Name: rawcensustractandblock, Length: 99292, dtype: int64

In [18]:
# remove
property_2016['censustractandblock'].value_counts()

6.037920e+13    1171
6.037137e+13     881
6.037920e+13     811
6.059063e+13     807
6.059052e+13     806
                ...
6.037481e+13       1
6.059032e+13       1
6.037540e+13       1
6.059042e+13       1
6.037407e+13       1
Name: censustractandblock, Length: 96771, dtype: int64

In [19]:
# remove
property_2016['regionidneighborhood'].value_counts()

118208.0    32267
268496.0    23186
48570.0     21186
27080.0     18891
37739.0     18645
            ...
764146.0        4
275855.0        3
275287.0        3
764092.0        3
273552.0        1
Name: regionidneighborhood, Length: 528, dtype: int64

In [20]:
property_2016.drop(['parcelid', 'propertycountylandusecode', 'propertyzoningdesc', 'rawcensustractandblock',
                   'censustractandblock', 'regionidneighborhood'], axis = 1, inplace = True)
property_2017.drop(['parcelid', 'propertycountylandusecode', 'propertyzoningdesc', 'rawcensustractandblock',
                   'censustractandblock', 'regionidneighborhood'], axis = 1, inplace = True)

In [22]:
for col in property_2016.columns:
    print(col)
    print(property_2016[col].value_counts())
    print("==================================")

airconditioningtypeid
1.0     742364
13.0     58457
5.0       8795
11.0      1818
12.0        59
9.0         19
3.0          7
Name: airconditioningtypeid, dtype: int64
==================================
architecturalstyletypeid
7.0     5251
8.0      380
2.0      201
21.0     150
3.0       58
5.0       19
27.0       1
10.0       1
Name: architecturalstyletypeid, dtype: int64
==================================
basementsqft
1528.0    25
700.0     21
240.0     21
100.0     18
144.0     16
          ..
874.0      1
1288.0     1
1646.0     1
1232.0     1
802.0      1
Name: basementsqft, Length: 751, dtype: int64
==================================
bathroomcnt
2.00     1218664
3.00      629351
1.00      499330
2.50      206856
4.00      132076
0.00      116614
1.50       45885
5.00       38241
3.50       30755
4.50       19017
6.00       16252
7.00        6149
5.50        5747
8.00        4537
9.00        1329
6.50        1217
10.00        500
7.50         380
12.00        265
11.00        207
8.50         106
13.00         52
9.50          50
14.00         45
16.00         30
15.00         24
0.50          17
18.00         15
10.50         12
20.00         10
17.00          7
1.75           5
11.50          3
19.00          3
12.50          2
19.50          1
14.50          1
Name: bathroomcnt, dtype: int64
==================================
bedroomcnt
3.0     1169462
4.0      727052
2.0      605367
5.0      181222
0.0      121466
1.0       86610
6.0       48563
8.0       13555
7.0       12744
9.0        4293
10.0       1726
12.0        981
11.0        439
13.0         89
14.0         73
16.0         65
15.0         26
20.0         13
18.0         10
17.0          8
19.0          3
Name: bedroomcnt, dtype: int64
==================================
buildingclasstypeid
4.0    9265
3.0    3161
2.0      81
1.0      65
5.0      57
Name: buildingclasstypeid, dtype: int64
==================================
buildingqualitytypeid
7.0     1133238
4.0      692160
1.0       69467
10.0      39713
12.0       3692
6.0          94
8.0          51
9.0          25
5.0          21
11.0         19
3.0           6
2.0           2
Name: buildingqualitytypeid, dtype: int64
==================================
calculatedbathnbr
2.0     1218652
3.0      629351
1.0      499322
2.5      206563
4.0      132076
1.5       45564
5.0       38241
3.5       30669
4.5       18959
6.0       16252
7.0        6149
5.5        5731
8.0        4537
9.0        1329
6.5        1204
10.0        500
7.5         377
12.0        265
11.0        207
8.5         102
13.0         52
9.5          50
14.0         45
16.0         30
15.0         24
18.0         15
10.5         12
20.0         10
17.0          7
11.5          3
19.0          3
12.5          2
14.5          1
19.5          1
Name: calculatedbathnbr, dtype: int64
==================================
decktypeid
66.0    17096
Name: decktypeid, dtype: int64
==================================
finishedfloor1squarefeet
1252.0    923
1233.0    864
1120.0    705
1226.0    616
1612.0    597
         ...
4635.0      1
5271.0      1
4917.0      1
5859.0      1
3475.0      1
Name: finishedfloor1squarefeet, Length: 4604, dtype: int64
==================================
calculatedfinishedsquarefeet
1440.0     8946
1344.0     7203
1200.0     7098
960.0      6014
1120.0     5918
           ...
35296.0       1
14129.0       1
9631.0        1
18154.0       1
13701.0       1
Name: calculatedfinishedsquarefeet, Length: 12587, dtype: int64
==================================
finishedsquarefeet12
1440.0     6941
1200.0     6636
1344.0     6235
1120.0     5660
1080.0     5611
           ...
7275.0        1
10866.0       1
136.0         1
12365.0       1
11066.0       1
Name: finishedsquarefeet12, Length: 10670, dtype: int64
==================================
finishedsquarefeet13
1440.0    1571
1344.0     709
1248.0     453
1536.0     355
720.0      245
          ...
1311.0       1
2240.0       1
2244.0       1
300.0        1
468.0        1
Name: finishedsquarefeet13, Length: 250, dtype: int64
==================================
finishedsquarefeet15
1536.0     647
1728.0     429
1600.0     415
1440.0     413
1800.0     402
          ...
10348.0      1
8552.0       1
8605.0       1
5857.0       1
35323.0      1
Name: finishedsquarefeet15, Length: 8816, dtype: int64
==================================
finishedsquarefeet50
1252.0    923
1233.0    864
1120.0    705
1226.0    616
1612.0    597
         ...
4231.0      1
2887.0      1
6152.0      1
4344.0      1
6325.0      1
Name: finishedsquarefeet50, Length: 4802, dtype: int64
==================================
finishedsquarefeet6
952.0     101
800.0      90
3820.0     88
720.0      74
600.0      68
         ...
2963.0      1
3445.0      1
412.0       1
3486.0      1
2853.0      1
Name: finishedsquarefeet6, Length: 4251, dtype: int64
==================================
fips
6037.0    2009362
6059.0     741565
6111.0     222853
Name: fips, dtype: int64
==================================
fireplacecnt
1.0    269643
2.0     34407
3.0      7696
4.0       710
5.0       126
6.0        32
7.0        15
9.0         6
8.0         2
Name: fireplacecnt, dtype: int64
==================================
fullbathcnt
2.0     1425661
3.0      660139
1.0      544928
4.0      151004
5.0       43918
6.0       17198
7.0        6409
8.0        4557
9.0        1339
10.0        498
12.0        263
11.0        204
13.0         53
14.0         45
16.0         30
15.0         23
18.0         15
20.0         10
17.0          7
19.0          4
Name: fullbathcnt, dtype: int64
==================================
garagecarcnt
2.0     660462
1.0     177579
3.0      19634
0.0      14005
4.0       8495
5.0       1705
6.0        575
7.0        266
8.0        181
9.0        127
10.0        78
11.0        62
12.0        41
13.0        16
14.0        14
15.0         9
17.0         4
19.0         3
16.0         3
20.0         2
21.0         2
24.0         2
18.0         1
25.0         1
Name: garagecarcnt, dtype: int64
==================================
garagetotalsqft
0.0       196752
400.0      33443
360.0      29703
441.0      26753
462.0      25476
           ...
3005.0         1
50.0           1
1317.0         1
6462.0         1
1911.0         1
Name: garagetotalsqft, Length: 2240, dtype: int64
==================================
hashottuborspa
True    69014
Name: hashottuborspa, dtype: int64
==================================
heatingorsystemtypeid
2.0     1156830
7.0      595453
6.0       27480
24.0      21107
20.0       3216
13.0       1342
18.0        586
1.0         262
14.0         41
10.0         39
12.0         25
11.0         16
21.0          3
19.0          1
Name: heatingorsystemtypeid, dtype: int64
==================================
latitude
33984600.0    862
33708500.0    760
34056700.0    740
34171800.0    611
33766300.0    568
             ...
33489454.0      1
34105817.0      1
33478289.0      1
33590150.0      1
33441312.0      1
Name: latitude, Length: 852325, dtype: int64
==================================
longitude
-118390000.0    1718
-118438000.0    1585
-118389000.0    1568
-118252000.0    1402
-118432000.0    1371
                ...
-117731293.0       1
-117601943.0       1
-118317006.0       1
-118652046.0       1
-118640167.0       1
Name: longitude, Length: 1042550, dtype: int64
==================================
lotsizesquarefeet
6000.0      44730
5000.0      17546
7200.0      15383
7000.0      11956
6500.0      11624
            ...
63040.0         1
434813.0        1
28664.0         1
111611.0        1
39154.0         1
Name: lotsizesquarefeet, Length: 69953, dtype: int64
==================================
poolcnt
1.0    517534
Name: poolcnt, dtype: int64
==================================
poolsizesum
450.0     3179
400.0      972
480.0      917
500.0      828
512.0      826
          ...
169.0        1
181.0        1
807.0        1
1004.0       1
1121.0       1
Name: poolsizesum, Length: 907, dtype: int64
==================================
pooltypeid10
1.0    36939
Name: pooltypeid10, dtype: int64
==================================
pooltypeid2
1.0    32075
Name: pooltypeid2, dtype: int64
==================================
pooltypeid7
1.0    485459
Name: pooltypeid7, dtype: int64
==================================
propertylandusetypeid

261.0    2148362
266.0     481067
246.0     114888
269.0      61469
263.0      58438
248.0      40325
247.0      40022
31.0        9462
265.0       9421
47.0        4314
260.0       2754
267.0       1817
275.0       1201
264.0        204
270.0         36
Name: propertylandusetypeid, dtype: int64
==================================
regionidcity
12447.0    670925
46298.0     93470
16764.0     59802
52650.0     58234
25218.0     56962
            ...
27512.0        12
36078.0        12
47913.0         7
3980.0          6
40633.0         5
Name: regionidcity, Length: 186, dtype: int64
==================================
regionidcounty
3101.0    2009362
1286.0     741565
2061.0     222853
Name: regionidcounty, dtype: int64
==================================
regionidzip
96987.0    22021
96193.0    21759
97118.0    20612
97319.0    20310
96964.0    19898
           ...
96068.0        1
97096.0        1
96313.0        1
96258.0        1
96453.0        1
Name: regionidzip, Length: 405, dtype: int64
==================================
roomcnt
0.0     2308879
6.0      178357
7.0      156397
8.0      120227
5.0       99582
9.0       45241
4.0       42320
10.0      10862
3.0        6289
11.0       3021
12.0       1097
2.0         751
13.0        313
14.0        156
1.0          77
15.0         67
16.0         35
18.0         22
30.0         14
17.0          9
19.0          6
21.0          4
20.0          3
84.0          1
52.0          1
22.0          1
24.0          1
42.0          1
67.0          1
56.0          1
40.0          1
96.0          1
45.0          1
77.0          1
31.0          1
86.0          1
Name: roomcnt, dtype: int64
==================================
storytypeid
7.0    1624
Name: storytypeid, dtype: int64
==================================
threequarterbathnbr
1.0    308959
2.0      2338
3.0       261
4.0        46
5.0        16
6.0         9
7.0         2
Name: threequarterbathnbr, dtype: int64
==================================
typeconstructiontypeid
6.0     6670
4.0       59
13.0      14
10.0       3
11.0       1
Name: typeconstructiontypeid, dtype: int64
==================================
unitcnt
1.0      1780051
2.0       115652
4.0        39877
3.0        39830
5.0          588
          ...
102.0          1
118.0          1
53.0           1
685.0          1
246.0          1
Name: unitcnt, Length: 146, dtype: int64
==================================
yardbuildingsqft17
240.0     3190
200.0     2980
300.0     2272
180.0     1492
288.0     1443
          ...
1511.0       1
1079.0       1
1391.0       1
1869.0       1
1911.0       1
Name: yardbuildingsqft17, Length: 1636, dtype: int64
==================================
yardbuildingsqft26
120.0     91
100.0     69
240.0     61
160.0     55
144.0     53
          ..
595.0      1
553.0      1
551.0      1
1182.0     1
423.0      1
Name: yardbuildingsqft26, Length: 594, dtype: int64
==================================
yearbuilt
1955.0    88586
1950.0    76142
1954.0    73307
1953.0    67085
1956.0    65736
          ...
1823.0        1
1807.0        1
1805.0        1
1840.0        1
1877.0        1
Name: yearbuilt, Length: 168, dtype: int64
==================================
numberofstories
1.0     424186
2.0     242125
3.0      15678
4.0         58
5.0         11
6.0          4
7.0          2
14.0         1
8.0          1
41.0         1
20.0         1
17.0         1
Name: numberofstories, dtype: int64
==================================
fireplaceflag
True    5163
Name: fireplaceflag, dtype: int64
==================================
structuretaxvaluedollarcnt
100000.0      1880
102461.0      1578
104510.0      1513
200000.0      1418
107401.0      1411
              ...
13209055.0       1
308118.0         1
680003.0         1
442564.0         1
366635.0         1
Name: structuretaxvaluedollarcnt, Length: 426150, dtype: int64
==================================
taxvaluedollarcnt
9.0         1889
400000.0    1572
350000.0    1511
450000.0    1459
500000.0    1339
            ...
686822.0       1
638240.0       1
395276.0       1
422793.0       1
417363.0       1
Name: taxvaluedollarcnt, Length: 638920, dtype: int64
==================================
assessmentyear
2015.0    2972420
2014.0       1306
2012.0         26
2004.0          6
2013.0          4
2003.0          3
2001.0          3
2009.0          2
2010.0          2
2005.0          2
2011.0          1
2002.0          1
2000.0          1
2016.0          1
Name: assessmentyear, dtype: int64
==================================
landtaxvaluedollarcnt
20980.0     3804
22414.0     2474
16275.0     2377
19149.0     2218
9.0         2172
            ...
635349.0       1
150696.0       1
392506.0       1
191072.0       1
516704.0       1
Name: landtaxvaluedollarcnt, Length: 531408, dtype: int64
==================================
taxamount
345.72      171
1844.16     124
1045.88     110
5.02        103
1481.24     102
           ...
23081.36      1
3795.69       1
5237.10       1
6315.91       1
19517.64      1
Name: taxamount, Length: 1045757, dtype: int64
==================================
taxdelinquencyflag
Y    56462
Name: taxdelinquencyflag, dtype: int64
==================================
taxdelinquencyyear
15.0    26068
14.0    16826
13.0     4632
12.0     3124
11.0     2350
10.0     1552
9.0      1016
8.0       501
7.0       236
6.0        71
5.0        23
4.0        16
3.0         5
95.0        5
92.0        5
99.0        4
2.0         4
98.0        3
93.0        3
1.0         2
0.0         2
91.0        2
90.0        2
94.0        2
97.0        2
79.0        2
82.0        1
88.0        1
86.0        1
84.0        1
96.0        1
87.0        1
Name: taxdelinquencyyear, dtype: int64
==================================

In [23]:
cat_col = ['airconditioningtypeid', 'architecturalstyletypeid', 'buildingclasstypeid', 'buildingqualitytypeid',
           'decktypeid', 'fips', 'hashottuborspa', 'heatingorsystemtypeid', 'poolcnt', 'poolsizesum', 
           'pooltypeid10', 'pooltypeid2', 'pooltypeid7', 'propertylandusetypeid', 'regionidcity', 'regionidcounty', 
           'regionidzip','storytypeid', 'typeconstructiontypeid', 'fireplaceflag', 'taxdelinquencyflag']

numeric_col = ['basementsqft', 'bathroomcnt', 'bedroomcnt', 'calculatedbathnbr', 'finishedfloor1squarefeet', 
               'calculatedfinishedsquarefeet', 'finishedsquarefeet12', 'finishedsquarefeet13', 
               'finishedsquarefeet15', 'finishedsquarefeet50', 'finishedsquarefeet6', 'fireplacecnt', 
               'fullbathcnt', 'garagecarcnt', 'garagetotalsqft', 'latitude', 'longitude', 'lotsizesquarefeet', 
               'roomcnt', 'threequarterbathnbr', 'unitcnt', 'yardbuildingsqft17', 'yardbuildingsqft26', 
               'yearbuilt', 'numberofstories', 'structuretaxvaluedollarcnt', 'taxvaluedollarcnt', 'assessmentyear', 
               'landtaxvaluedollarcnt', 'taxamount', 'taxdelinquencyyear']

In [24]:
len(cat_col)

21

In [25]:
len(numeric_col)

31

In [26]:
property_2016.shape

(2985217, 52)